logging:
  level:
    io.zenwave360.example: DEBUG
    org.springframework.security: DEBUG
#    org.apache.kafka: DEBUG
spring:
  security:
    user:
      name: user
      password: password
      roles: USER
  jpa.hibernate.ddl-auto: create
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    stream:
      function:
        definition: on-customer-event;on-customer-address-event;
      bindings:
        on-customer-event-out-0:
          destination: customer.events
        on-customer-address-event-out-0:
          destination: customer.address-events

            
